## Mod Properties
mod_name=DynamicTreesFruitsDelight
mod_license=MIT
mod_id=dtfruitsdelight
mod_version=1.0.1
mod_group_id=group.dtfruitsdelight
mod_authors=GoddessStorm
mod_credits=GoddessStorm for forked port,Groupix05 for the template
mod_description=Dynamic Trees Addon for Fruits Delight
version_type=beta

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neo_version=21.1.172
neo_version_range=[21.1.0,)
loader_version_range=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Java Stuff
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.debug=false
